run web tests, upload test coverage to deepsource

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -71,6 +71,36 @@ definitions:
           # clear CloudFront cache after successful S3 deployment
           - bash ./scripts/invalidate-cache
 
+    - step: &test
+        name: Test the live API
+        trigger: automatic
+        clone: 
+          enabled: true
+        script:
+          # wait for lambdas to finish updating
+          - git clone git@bitbucket.org:Makpar/test-harness.git
+          - cd test-harness/python
+          - sleep 15s
+          - |
+            if [ "${BITBUCKET_BRANCH}" == "Prod" ] 
+            then
+                export BRANCH=""
+            else
+              export BRANCH="-${BITBUCKET_BRANCH}"
+            fi
+          - export FRONTEND_HOST_URL=https://${SUBDOMAIN}${BRANCH,,}.${DOMAIN}
+          - chmod +x ./configure
+          - ./configure
+          - mkdir tmp
+          # return true so pipeline doesn't fail on test failures
+          - coverage run --source="." -m behave -t "@Web" --no-skipped --summary --junit --junit-directory ./tmp || true
+          - coverage xml
+          # upload test coverage to DeepSource
+          - cd ../..
+          - export DEEPSOURCE_DSN
+          - deepsource report --analyzer test-coverage --key python --value-file ./test-harness/python/coverage.xml
+
+
 pipelines:
   # Repository Wide Workflows: Tests, Scans and Static Code Analysis
   default:
@@ -90,21 +120,25 @@ pipelines:
       - step:
           <<: *deploy
           deployment: Production
+      - step: *test
     Test: 
       - step: *install
       - step: *build
       - step: 
           <<: *deploy
           deployment: Test
+      - step: *test
     Staging:
       - step: *install
       - step: *build
       - step:
           <<: *deploy
           deployment: Staging
+      - step: *test
     Dev:
       - step: *install
       - step: *build
       - step: 
           <<: *deploy
           deployment: Development
+      - step: *test
